### ISSUE TITLE
[JOSS Review] - PingjunChen

### ISSUE THREAD

**Issue by PingjunChen** [choosehappy/HoverFast#2]
Hey,

I am reviewing the checklist https://github.com/openjournals/joss-reviews/issues/7022#issuecomment-2243749071. HoverFast is in good shape overall. Two minor issues:

1. The command line for training the model using docker/singularity in the "README/Training/Train model" part, "-l training_metrics" should be "-o training_metrics". 
2. "scikit-learn’s [@scikit-learn] regionprops and watershed" inside [paper/paper.md](https://github.com/choosehappy/HoverFast/tree/main/paper) should be scikit-image.

**Comment by JulienMassonnet** [comment]
Hi @PingjunChen,

Thank you very much for your feedback. I have made the necessary modifications and recompiled the paper to verify if it's working. Please let me know if there are any other points you would like to address.
